### ISSUE TITLE
[PE-D] Delete error message is inconsistent

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W11-2/tp#220]
![image.png](https://raw.githubusercontent.com/gordonlzy/ped/main/files/07daffd2-74cb-4178-8d72-76bae2528910.png)

![image.png](https://raw.githubusercontent.com/gordonlzy/ped/main/files/4af4fa13-d11c-4eea-8066-ce6869b647c6.png)

Both commands having the right format but having invalid number input display different error message.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: gordonlzy/ped#12

**Comment by Gabau** [comment]
Should result in invalid integer
