### ISSUE TITLE
[PE-D] Mark shows the other field as optional but eg status does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W11-2/tp#222]
![image.png](https://raw.githubusercontent.com/gordonlzy/ped/main/files/3eac6adc-3e42-4544-ba61-b48752d5eb02.png)

It seems that only index and name are used to identify the staff but other fields that are not unique are put as optional here.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: gordonlzy/ped#14

**Comment by Gabau** [comment]
Mark marks groups of staff who satisfy the queried fields. Missed this in the documentation, same for `view`, `unmark`, `viewSchedule`.
