### ISSUE TITLE
[PE-D] Using mark feature with example in UG, does not seem to be working and error message does not help

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W11-2/tp#228]
![image.png](https://raw.githubusercontent.com/yulonglim/ped/main/files/eb7e4306-3518-4483-bdd5-5cd45b75c217.png)

![image.png](https://raw.githubusercontent.com/yulonglim/ped/main/files/8fa7951c-edc3-4840-9711-bdb11c5150be.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: yulonglim/ped#7

**Comment by Gabau** [comment]
Tag wasn't updated to da/ instead of d/
