### ISSUE TITLE
Salary and timetable are mismatched, which may lead to confusion

### ISSUE THREAD

**Issue by IrvingHe000** [AY2122S1-CS2103T-W11-2/tp#242]
Currently, the schedule shows the work of the worker in the current week, but the salary `istaff` calculates is the total salary, which may lead to confusion that users may think there is a bug.
<img width="1829" alt="Screenshot 2021-11-03 at 12 07 02 AM" src="https://user-images.githubusercontent.com/69430003/139896127-3ef3b4e2-e422-485a-b370-fe99c48b9c95.png">
.

**Comment by Gabau** [comment]
Isn't it better to show the salary for the month?

**Comment by IrvingHe000** [comment]
Yeah I think monthly is better but just need more clarifications, like the salary is for the month and whether it is determined by the current date to decide the month etc. Maybe can both show in the documentation and the message.
