### ISSUE TITLE
View shift shows an output without the correct staff

### ISSUE THREAD

**Issue by Gabau** [AY2122S1-CS2103T-W11-2/tp#270]
![image](https://user-images.githubusercontent.com/70463178/140534342-7eb81301-5849-4a31-a63a-db8a4acb5a95.png)

Command used:
`viewShift`

Expected, staff in current shift, got noone

**Comment by fullfatwasabi** [comment]
I think viewShift without any fields was meant to find the staff working on the current shift, do you wanna change how this works?
