### ISSUE TITLE
mark leads salary and schedule inconsistent 

### ISSUE THREAD

**Issue by IrvingHe000** [AY2122S1-CS2103T-W11-2/tp#275]
After I have marked a period, I add a new shift to the schedule. I supposed that the shift will be removed automatically, but although the salary is still 0, it's shown on the schedule:

<img width="1330" alt="Screenshot 2021-11-06 at 2 06 47 AM" src="https://user-images.githubusercontent.com/69430003/140558222-8c482fe1-b15d-4800-ac4a-73deacb8b2a6.png">

**Comment by Gabau** [comment]
Mark command does not remove the shift, it just marks the staff as absent. Will be displayed in the staff view?

**Comment by IrvingHe000** [comment]
Oh then I think this is not a issue, just need to fix the former one
